version: "3.8"
services:
  auth_service:
    build: ./auth_service
    ports:
      - "8001:8001"

  ontology_service:
    build: ./ontology_service
    ports:
      - "8002:8002"

  qa_service:
    build: ./qa_service
    ports:
      - "8003:8003"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
