openapi: 3.0.0
info:
  title: Ontology API
  version: 1.0.0
  description: Programming languages ontology API

paths:
  /onto/query/:
    get:
      parameters:
        - name: entity
          in: query
          required: true
          schema:
            type: string
        - name: predicate
          in: query
          required: true
          schema:
            type: string
        - name: direction
          in: query
          required: true
          schema:
            type: string
            enum: [forward, backward]
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QueryResult'

  /onto/predicates/:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /onto/languages/:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /onto/language/{language}/details:
    get:
      parameters:
        - name: language
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LanguageDetails'

  /onto/entity_relations/{entity}:
    get:
      parameters:
        - name: entity
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityRelations'

components:
  schemas:
    QueryResult:
      type: object
      properties:
        name:
          type: string
        link:
          type: string

    LanguageDetails:
      type: object
      properties:
        paradigms:
          type: array
          items:
            type: string
        frameworks:
          type: array
          items:
            type: string
        repositories:
          type: array
          items:
            $ref: '#/components/schemas/Repository'

    Repository:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
        watchers:
          type: integer

    EntityRelations:
      type: object
      properties:
        forward_relations:
          type: array
          items:
            $ref: '#/components/schemas/Relation'
        backward_relations:
          type: array
          items:
            $ref: '#/components/schemas/Relation'

    Relation:
      type: object
      properties:
        predicate:
          type: string
        object:
          type: string
        subject:
          type: string