openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: User authentication and management API

paths:
  /auth/register:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '200':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Email exists

  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '401':
          description: Invalid credentials

  /auth/users/me:
    get:
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /auth/logout:
    post:
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Logged out

components:
  schemas:
    UserCreate:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - username
        - email
        - password

    User:
      type: object
      properties:
        username:
          type: string
        email:
          type: string

    Token:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer